export const PROPOSAL_STATE_PENDING = "PENDING";
export const PROPOSAL_STATE_ACTIVE = "ACTIVE";
export const PROPOSAL_STATE_CANCELED = "CANCELED";
export const PROPOSAL_STATE_DEFEATED = "DEFEATED";
export const PROPOSAL_STATE_SUCCEEDED = "SUCCEEDED"
export const PROPOSAL_STATE_QUEUED = "QUEUED";
export const PROPOSAL_STATE_EXPIRED = "EXPIRED";
export const PROPOSAL_STATE_EXECUTED = "EXECUTED";